### PR TITLE
Move to get haskell packages from CHaP

### PR DESCRIPTION
**Pull request by michaelpj**
WIP, probably needs to put some of the `source-repository-package`s back corresponding to the pre-release stuff you depend on. But I'm out of time for today!

### CODE REVIEW

**Comment by michaelpj** [comment]
Okay, this works now.

- Bumped to use GHC 8.10.7
- Updated haskell.nix and used haskell.nix's nixpkgs for better caching
- Removed lots of now-unnecessary or dead config
- Remove all s-r-ps except the necessary `ouroboros-network` one

I haven't written a CONTRIBUTING doc for this repo, I just referenced `ouroboros-network` for now.

**Comment by coot** [comment]
@michaelpj I overlooked your PR and I merged #15 today, but there's more in your PR. Also note that `ekg-forward-0.3.0.0` was pushed to `CHaP` in input-output-hk/cardano-haskell-packages#78.

**Comment by michaelpj** [comment]
Yes, this also fixes the nix setup. I'll rebase it. `ekg-forward` being released is independent of this change.

**Comment by michaelpj** [comment]
@coot ready for another look

**Review by coot — APPROVED** [review]

**Pull request merged**
