### PR TITLE
cabal-project: bump ouroboros-network dependency

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by coot** [comment]
It seems one can merge changes to this repo without a review.  Is this by design, or was this overlooked?

**Review by karknu — APPROVED** [review]
LGTM, just fix the warning.

**Comment by coot** [comment]
This cannot be yet merged, as I haven't updated `nix` hash of `ouroboros-netowrk`.  At the moment, none of my machines has nix and this repo does not provide the nix job which would print it.l

**Comment by coot** [comment]
I got the correct `ouroboros-network` hash.

**Pull request merged**
